"""
✨ `HarvestListing_KeyOutput` returns the primary key fields of table type `HarvestListing`.

It has the same format as `HarvestListing_Key`, but is only used as mutation return value.
"""
scalar HarvestListing_KeyOutput
"""
✨ `Notification_KeyOutput` returns the primary key fields of table type `Notification`.

It has the same format as `Notification_Key`, but is only used as mutation return value.
"""
scalar Notification_KeyOutput
"""
✨ `Order_KeyOutput` returns the primary key fields of table type `Order`.

It has the same format as `Order_Key`, but is only used as mutation return value.
"""
scalar Order_KeyOutput
"""
✨ `Pond_KeyOutput` returns the primary key fields of table type `Pond`.

It has the same format as `Pond_Key`, but is only used as mutation return value.
"""
scalar Pond_KeyOutput
"""
✨ `SensorReading_KeyOutput` returns the primary key fields of table type `SensorReading`.

It has the same format as `SensorReading_Key`, but is only used as mutation return value.
"""
scalar SensorReading_KeyOutput
"""
✨ `SmartRecommendation_KeyOutput` returns the primary key fields of table type `SmartRecommendation`.

It has the same format as `SmartRecommendation_Key`, but is only used as mutation return value.
"""
scalar SmartRecommendation_KeyOutput
"""
✨ `User_KeyOutput` returns the primary key fields of table type `User`.

It has the same format as `User_Key`, but is only used as mutation return value.
"""
scalar User_KeyOutput
"""
✨ Generated data input type for table 'HarvestListing'. It includes all necessary fields for creating or upserting rows into table.
"""
input HarvestListing_Data {
  """
  ✨ Generated from Field `HarvestListing`.`id` of type `UUID!`
  """
  id: UUID
  """
  ✨ `_expr` server value variant of `id` (✨ Generated from Field `HarvestListing`.`id` of type `UUID!`)
  """
  id_expr: UUID_Expr @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `HarvestListing`.`farmerId` of type `UUID!`
  """
  farmerId: UUID
  """
  ✨ `_expr` server value variant of `farmerId` (✨ Generated from Field `HarvestListing`.`farmerId` of type `UUID!`)
  """
  farmerId_expr: UUID_Expr @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `HarvestListing`.`farmer` of type `User!`
  """
  farmer: User_Key @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `HarvestListing`.`harvestDate` of type `Date`
  """
  harvestDate: Date
  """
  ✨ `_date` server value variant of `harvestDate` (✨ Generated from Field `HarvestListing`.`harvestDate` of type `Date`)
  """
  harvestDate_date: Date_Relative @fdc_forbiddenInVariables
  """
  ✨ `_expr` server value variant of `harvestDate` (✨ Generated from Field `HarvestListing`.`harvestDate` of type `Date`)
  """
  harvestDate_expr: Date_Expr @fdc_forbiddenInVariables
  """
  ✨ `_update` server value variant of `harvestDate` (✨ Generated from Field `HarvestListing`.`harvestDate` of type `Date`)
  """
  harvestDate_update: [Date_Update!] @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `HarvestListing`.`pricePerUnit` of type `Float!`
  """
  pricePerUnit: Float
  """
  ✨ `_expr` server value variant of `pricePerUnit` (✨ Generated from Field `HarvestListing`.`pricePerUnit` of type `Float!`)
  """
  pricePerUnit_expr: Float_Expr @fdc_forbiddenInVariables
  """
  ✨ `_update` server value variant of `pricePerUnit` (✨ Generated from Field `HarvestListing`.`pricePerUnit` of type `Float!`)
  """
  pricePerUnit_update: [Float_Update!] @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `HarvestListing`.`quantity` of type `Int!`
  """
  quantity: Int
  """
  ✨ `_expr` server value variant of `quantity` (✨ Generated from Field `HarvestListing`.`quantity` of type `Int!`)
  """
  quantity_expr: Int_Expr @fdc_forbiddenInVariables
  """
  ✨ `_update` server value variant of `quantity` (✨ Generated from Field `HarvestListing`.`quantity` of type `Int!`)
  """
  quantity_update: [Int_Update!] @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `HarvestListing`.`species` of type `String!`
  """
  species: String
  """
  ✨ `_expr` server value variant of `species` (✨ Generated from Field `HarvestListing`.`species` of type `String!`)
  """
  species_expr: String_Expr @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `HarvestListing`.`status` of type `String!`
  """
  status: String
  """
  ✨ `_expr` server value variant of `status` (✨ Generated from Field `HarvestListing`.`status` of type `String!`)
  """
  status_expr: String_Expr @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `HarvestListing`.`orders_on_listing` of type `[Order!]!`
  """
  orders_on_listing: [Order_Data!]
}
"""
✨ Generated filter input type for table 'HarvestListing'. This input allows filtering objects using various conditions. Use `_or`, `_and`, and `_not` to compose complex filters.
"""
input HarvestListing_Filter {
  """
  Apply multiple filter conditions using `AND` logic.
  """
  _and: [HarvestListing_Filter!]
  """
  Negate the result of the provided filter condition.
  """
  _not: HarvestListing_Filter
  """
  Apply multiple filter conditions using `OR` logic.
  """
  _or: [HarvestListing_Filter!]
  """
  ✨ Generated from Field `HarvestListing`.`id` of type `UUID!`
  """
  id: UUID_Filter
  """
  ✨ Generated from Field `HarvestListing`.`farmerId` of type `UUID!`
  """
  farmerId: UUID_Filter
  """
  ✨ Generated from Field `HarvestListing`.`farmer` of type `User!`
  """
  farmer: User_Filter
  """
  ✨ Generated from Field `HarvestListing`.`harvestDate` of type `Date`
  """
  harvestDate: Date_Filter
  """
  ✨ Generated from Field `HarvestListing`.`pricePerUnit` of type `Float!`
  """
  pricePerUnit: Float_Filter
  """
  ✨ Generated from Field `HarvestListing`.`quantity` of type `Int!`
  """
  quantity: Int_Filter
  """
  ✨ Generated from Field `HarvestListing`.`species` of type `String!`
  """
  species: String_Filter
  """
  ✨ Generated from Field `HarvestListing`.`status` of type `String!`
  """
  status: String_Filter
  """
  ✨ Generated from Field `HarvestListing`.`orders_on_listing` of type `[Order!]!`
  """
  orders_on_listing: Order_ListFilter
}
"""
✨ Generated first-row input type for table 'HarvestListing'. This input selects the first row matching the filter criteria, ordered according to the specified conditions.
"""
input HarvestListing_FirstRow {
  """
  Order the result by the specified fields.
  """
  orderBy: [HarvestListing_Order!]
  """
  Filters rows based on the specified conditions.
  """
  where: HarvestListing_Filter
}
"""
✨ Generated having input type for table 'HarvestListing'. This input allows you to filter groups during aggregate queries using various conditions. Use `_or`, `_and`, and `_not` to compose complex filters.
"""
input HarvestListing_Having {
  """
  Apply multiple Having conditions using `AND` logic.
  """
  _and: [HarvestListing_Having!]
  """
  Whether to apply DISTINCT to the aggregate function.
  """
  _distinct: Boolean
  """
  Negate the result of the provided Having condition.
  """
  _not: HarvestListing_Having
  """
  Apply multiple Having conditions using `OR` logic.
  """
  _or: [HarvestListing_Having!]
  """
  ✨ Generated from Field `HarvestListing`.`_count` of type `Int!`
  """
  _count: Int_Filter
  """
  ✨ Generated from Field `HarvestListing`.`farmerId_count` of type `Int!`
  """
  farmerId_count: Int_Filter
  """
  ✨ Generated from Field `HarvestListing`.`harvestDate_count` of type `Int!`
  """
  harvestDate_count: Int_Filter
  """
  ✨ Generated from Field `HarvestListing`.`id_count` of type `Int!`
  """
  id_count: Int_Filter
  """
  ✨ Generated from Field `HarvestListing`.`pricePerUnit_count` of type `Int!`
  """
  pricePerUnit_count: Int_Filter
  """
  ✨ Generated from Field `HarvestListing`.`quantity_count` of type `Int!`
  """
  quantity_count: Int_Filter
  """
  ✨ Generated from Field `HarvestListing`.`species_count` of type `Int!`
  """
  species_count: Int_Filter
  """
  ✨ Generated from Field `HarvestListing`.`status_count` of type `Int!`
  """
  status_count: Int_Filter
  """
  ✨ Generated from Field `HarvestListing`.`pricePerUnit_sum` of type `Float`
  """
  pricePerUnit_sum: Float_Filter
  """
  ✨ Generated from Field `HarvestListing`.`quantity_sum` of type `Int`
  """
  quantity_sum: Int_Filter
  """
  ✨ Generated from Field `HarvestListing`.`pricePerUnit_avg` of type `Float`
  """
  pricePerUnit_avg: Float_Filter
  """
  ✨ Generated from Field `HarvestListing`.`quantity_avg` of type `Float`
  """
  quantity_avg: Float_Filter
  """
  ✨ Generated from Field `HarvestListing`.`harvestDate_min` of type `Date`
  """
  harvestDate_min: Date_Filter
  """
  ✨ Generated from Field `HarvestListing`.`pricePerUnit_min` of type `Float`
  """
  pricePerUnit_min: Float_Filter
  """
  ✨ Generated from Field `HarvestListing`.`quantity_min` of type `Int`
  """
  quantity_min: Int_Filter
  """
  ✨ Generated from Field `HarvestListing`.`harvestDate_max` of type `Date`
  """
  harvestDate_max: Date_Filter
  """
  ✨ Generated from Field `HarvestListing`.`pricePerUnit_max` of type `Float`
  """
  pricePerUnit_max: Float_Filter
  """
  ✨ Generated from Field `HarvestListing`.`quantity_max` of type `Int`
  """
  quantity_max: Int_Filter
}
"""
✨ Generated key input type for table 'HarvestListing'. It represents the primary key fields used to uniquely identify a row in the table.
"""
input HarvestListing_Key {
  """
  ✨ Generated from Field `HarvestListing`.`id` of type `UUID!`
  """
  id: UUID
  """
  ✨ `_expr` server value variant of `id` (✨ Generated from Field `HarvestListing`.`id` of type `UUID!`)
  """
  id_expr: UUID_Expr @fdc_forbiddenInVariables
}
"""
✨ Generated list filter input type for table 'HarvestListing'. This input applies filtering logic based on the count or existence of related objects that matches certain criteria.
"""
input HarvestListing_ListFilter {
  """
  The desired number of objects that match the condition (defaults to at least one).
  """
  count: Int_Filter = {gt:0}
  """
  Condition of the related objects to filter for.
  """
  exist: HarvestListing_Filter
}
"""
✨ Generated order input type for table 'HarvestListing'. This input defines the sorting order of rows in query results based on one or more fields.
"""
input HarvestListing_Order {
  """
  ✨ Generated from Field `HarvestListing`.`id` of type `UUID!`
  """
  id: OrderDirection
  """
  ✨ Generated from Field `HarvestListing`.`farmerId` of type `UUID!`
  """
  farmerId: OrderDirection
  """
  ✨ Generated from Field `HarvestListing`.`farmer` of type `User!`
  """
  farmer: User_Order
  """
  ✨ Generated from Field `HarvestListing`.`harvestDate` of type `Date`
  """
  harvestDate: OrderDirection
  """
  ✨ Generated from Field `HarvestListing`.`pricePerUnit` of type `Float!`
  """
  pricePerUnit: OrderDirection
  """
  ✨ Generated from Field `HarvestListing`.`quantity` of type `Int!`
  """
  quantity: OrderDirection
  """
  ✨ Generated from Field `HarvestListing`.`species` of type `String!`
  """
  species: OrderDirection
  """
  ✨ Generated from Field `HarvestListing`.`status` of type `String!`
  """
  status: OrderDirection
  """
  ✨ Generated from Field `HarvestListing`.`_count` of type `Int!`
  """
  _count: OrderDirection
  """
  ✨ Generated from Field `HarvestListing`.`farmerId_count` of type `Int!`
  """
  farmerId_count: OrderDirection
  """
  ✨ Generated from Field `HarvestListing`.`harvestDate_count` of type `Int!`
  """
  harvestDate_count: OrderDirection
  """
  ✨ Generated from Field `HarvestListing`.`id_count` of type `Int!`
  """
  id_count: OrderDirection
  """
  ✨ Generated from Field `HarvestListing`.`pricePerUnit_count` of type `Int!`
  """
  pricePerUnit_count: OrderDirection
  """
  ✨ Generated from Field `HarvestListing`.`quantity_count` of type `Int!`
  """
  quantity_count: OrderDirection
  """
  ✨ Generated from Field `HarvestListing`.`species_count` of type `Int!`
  """
  species_count: OrderDirection
  """
  ✨ Generated from Field `HarvestListing`.`status_count` of type `Int!`
  """
  status_count: OrderDirection
  """
  ✨ Generated from Field `HarvestListing`.`pricePerUnit_sum` of type `Float`
  """
  pricePerUnit_sum: OrderDirection
  """
  ✨ Generated from Field `HarvestListing`.`quantity_sum` of type `Int`
  """
  quantity_sum: OrderDirection
  """
  ✨ Generated from Field `HarvestListing`.`pricePerUnit_avg` of type `Float`
  """
  pricePerUnit_avg: OrderDirection
  """
  ✨ Generated from Field `HarvestListing`.`quantity_avg` of type `Float`
  """
  quantity_avg: OrderDirection
  """
  ✨ Generated from Field `HarvestListing`.`harvestDate_min` of type `Date`
  """
  harvestDate_min: OrderDirection
  """
  ✨ Generated from Field `HarvestListing`.`pricePerUnit_min` of type `Float`
  """
  pricePerUnit_min: OrderDirection
  """
  ✨ Generated from Field `HarvestListing`.`quantity_min` of type `Int`
  """
  quantity_min: OrderDirection
  """
  ✨ Generated from Field `HarvestListing`.`harvestDate_max` of type `Date`
  """
  harvestDate_max: OrderDirection
  """
  ✨ Generated from Field `HarvestListing`.`pricePerUnit_max` of type `Float`
  """
  pricePerUnit_max: OrderDirection
  """
  ✨ Generated from Field `HarvestListing`.`quantity_max` of type `Int`
  """
  quantity_max: OrderDirection
}
"""
✨ Generated data input type for table 'Notification'. It includes all necessary fields for creating or upserting rows into table.
"""
input Notification_Data {
  """
  ✨ Generated from Field `Notification`.`id` of type `UUID!`
  """
  id: UUID
  """
  ✨ `_expr` server value variant of `id` (✨ Generated from Field `Notification`.`id` of type `UUID!`)
  """
  id_expr: UUID_Expr @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `Notification`.`userId` of type `UUID!`
  """
  userId: UUID
  """
  ✨ `_expr` server value variant of `userId` (✨ Generated from Field `Notification`.`userId` of type `UUID!`)
  """
  userId_expr: UUID_Expr @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `Notification`.`user` of type `User!`
  """
  user: User_Key @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `Notification`.`createdAt` of type `Timestamp!`
  """
  createdAt: Timestamp
  """
  ✨ `_expr` server value variant of `createdAt` (✨ Generated from Field `Notification`.`createdAt` of type `Timestamp!`)
  """
  createdAt_expr: Timestamp_Expr @fdc_forbiddenInVariables
  """
  ✨ `_time` server value variant of `createdAt` (✨ Generated from Field `Notification`.`createdAt` of type `Timestamp!`)
  """
  createdAt_time: Timestamp_Relative @fdc_forbiddenInVariables
  """
  ✨ `_update` server value variant of `createdAt` (✨ Generated from Field `Notification`.`createdAt` of type `Timestamp!`)
  """
  createdAt_update: [Timestamp_Update!] @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `Notification`.`isRead` of type `Boolean!`
  """
  isRead: Boolean
  """
  ✨ `_expr` server value variant of `isRead` (✨ Generated from Field `Notification`.`isRead` of type `Boolean!`)
  """
  isRead_expr: Boolean_Expr @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `Notification`.`message` of type `String!`
  """
  message: String
  """
  ✨ `_expr` server value variant of `message` (✨ Generated from Field `Notification`.`message` of type `String!`)
  """
  message_expr: String_Expr @fdc_forbiddenInVariables
}
"""
✨ Generated filter input type for table 'Notification'. This input allows filtering objects using various conditions. Use `_or`, `_and`, and `_not` to compose complex filters.
"""
input Notification_Filter {
  """
  Apply multiple filter conditions using `AND` logic.
  """
  _and: [Notification_Filter!]
  """
  Negate the result of the provided filter condition.
  """
  _not: Notification_Filter
  """
  Apply multiple filter conditions using `OR` logic.
  """
  _or: [Notification_Filter!]
  """
  ✨ Generated from Field `Notification`.`id` of type `UUID!`
  """
  id: UUID_Filter
  """
  ✨ Generated from Field `Notification`.`userId` of type `UUID!`
  """
  userId: UUID_Filter
  """
  ✨ Generated from Field `Notification`.`user` of type `User!`
  """
  user: User_Filter
  """
  ✨ Generated from Field `Notification`.`createdAt` of type `Timestamp!`
  """
  createdAt: Timestamp_Filter
  """
  ✨ Generated from Field `Notification`.`isRead` of type `Boolean!`
  """
  isRead: Boolean_Filter
  """
  ✨ Generated from Field `Notification`.`message` of type `String!`
  """
  message: String_Filter
}
"""
✨ Generated first-row input type for table 'Notification'. This input selects the first row matching the filter criteria, ordered according to the specified conditions.
"""
input Notification_FirstRow {
  """
  Order the result by the specified fields.
  """
  orderBy: [Notification_Order!]
  """
  Filters rows based on the specified conditions.
  """
  where: Notification_Filter
}
"""
✨ Generated having input type for table 'Notification'. This input allows you to filter groups during aggregate queries using various conditions. Use `_or`, `_and`, and `_not` to compose complex filters.
"""
input Notification_Having {
  """
  Apply multiple Having conditions using `AND` logic.
  """
  _and: [Notification_Having!]
  """
  Whether to apply DISTINCT to the aggregate function.
  """
  _distinct: Boolean
  """
  Negate the result of the provided Having condition.
  """
  _not: Notification_Having
  """
  Apply multiple Having conditions using `OR` logic.
  """
  _or: [Notification_Having!]
  """
  ✨ Generated from Field `Notification`.`_count` of type `Int!`
  """
  _count: Int_Filter
  """
  ✨ Generated from Field `Notification`.`createdAt_count` of type `Int!`
  """
  createdAt_count: Int_Filter
  """
  ✨ Generated from Field `Notification`.`id_count` of type `Int!`
  """
  id_count: Int_Filter
  """
  ✨ Generated from Field `Notification`.`isRead_count` of type `Int!`
  """
  isRead_count: Int_Filter
  """
  ✨ Generated from Field `Notification`.`message_count` of type `Int!`
  """
  message_count: Int_Filter
  """
  ✨ Generated from Field `Notification`.`userId_count` of type `Int!`
  """
  userId_count: Int_Filter
  """
  ✨ Generated from Field `Notification`.`createdAt_min` of type `Timestamp`
  """
  createdAt_min: Timestamp_Filter
  """
  ✨ Generated from Field `Notification`.`createdAt_max` of type `Timestamp`
  """
  createdAt_max: Timestamp_Filter
}
"""
✨ Generated key input type for table 'Notification'. It represents the primary key fields used to uniquely identify a row in the table.
"""
input Notification_Key {
  """
  ✨ Generated from Field `Notification`.`id` of type `UUID!`
  """
  id: UUID
  """
  ✨ `_expr` server value variant of `id` (✨ Generated from Field `Notification`.`id` of type `UUID!`)
  """
  id_expr: UUID_Expr @fdc_forbiddenInVariables
}
"""
✨ Generated list filter input type for table 'Notification'. This input applies filtering logic based on the count or existence of related objects that matches certain criteria.
"""
input Notification_ListFilter {
  """
  The desired number of objects that match the condition (defaults to at least one).
  """
  count: Int_Filter = {gt:0}
  """
  Condition of the related objects to filter for.
  """
  exist: Notification_Filter
}
"""
✨ Generated order input type for table 'Notification'. This input defines the sorting order of rows in query results based on one or more fields.
"""
input Notification_Order {
  """
  ✨ Generated from Field `Notification`.`id` of type `UUID!`
  """
  id: OrderDirection
  """
  ✨ Generated from Field `Notification`.`userId` of type `UUID!`
  """
  userId: OrderDirection
  """
  ✨ Generated from Field `Notification`.`user` of type `User!`
  """
  user: User_Order
  """
  ✨ Generated from Field `Notification`.`createdAt` of type `Timestamp!`
  """
  createdAt: OrderDirection
  """
  ✨ Generated from Field `Notification`.`isRead` of type `Boolean!`
  """
  isRead: OrderDirection
  """
  ✨ Generated from Field `Notification`.`message` of type `String!`
  """
  message: OrderDirection
  """
  ✨ Generated from Field `Notification`.`_count` of type `Int!`
  """
  _count: OrderDirection
  """
  ✨ Generated from Field `Notification`.`createdAt_count` of type `Int!`
  """
  createdAt_count: OrderDirection
  """
  ✨ Generated from Field `Notification`.`id_count` of type `Int!`
  """
  id_count: OrderDirection
  """
  ✨ Generated from Field `Notification`.`isRead_count` of type `Int!`
  """
  isRead_count: OrderDirection
  """
  ✨ Generated from Field `Notification`.`message_count` of type `Int!`
  """
  message_count: OrderDirection
  """
  ✨ Generated from Field `Notification`.`userId_count` of type `Int!`
  """
  userId_count: OrderDirection
  """
  ✨ Generated from Field `Notification`.`createdAt_min` of type `Timestamp`
  """
  createdAt_min: OrderDirection
  """
  ✨ Generated from Field `Notification`.`createdAt_max` of type `Timestamp`
  """
  createdAt_max: OrderDirection
}
"""
✨ Generated data input type for table 'Order'. It includes all necessary fields for creating or upserting rows into table.
"""
input Order_Data {
  """
  ✨ Generated from Field `Order`.`id` of type `UUID!`
  """
  id: UUID
  """
  ✨ `_expr` server value variant of `id` (✨ Generated from Field `Order`.`id` of type `UUID!`)
  """
  id_expr: UUID_Expr @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `Order`.`buyerId` of type `UUID!`
  """
  buyerId: UUID
  """
  ✨ `_expr` server value variant of `buyerId` (✨ Generated from Field `Order`.`buyerId` of type `UUID!`)
  """
  buyerId_expr: UUID_Expr @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `Order`.`listingId` of type `UUID!`
  """
  listingId: UUID
  """
  ✨ `_expr` server value variant of `listingId` (✨ Generated from Field `Order`.`listingId` of type `UUID!`)
  """
  listingId_expr: UUID_Expr @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `Order`.`buyer` of type `User!`
  """
  buyer: User_Key @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `Order`.`listing` of type `HarvestListing!`
  """
  listing: HarvestListing_Key @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `Order`.`quantity` of type `Int!`
  """
  quantity: Int
  """
  ✨ `_expr` server value variant of `quantity` (✨ Generated from Field `Order`.`quantity` of type `Int!`)
  """
  quantity_expr: Int_Expr @fdc_forbiddenInVariables
  """
  ✨ `_update` server value variant of `quantity` (✨ Generated from Field `Order`.`quantity` of type `Int!`)
  """
  quantity_update: [Int_Update!] @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `Order`.`status` of type `String!`
  """
  status: String
  """
  ✨ `_expr` server value variant of `status` (✨ Generated from Field `Order`.`status` of type `String!`)
  """
  status_expr: String_Expr @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `Order`.`totalAmount` of type `Float!`
  """
  totalAmount: Float
  """
  ✨ `_expr` server value variant of `totalAmount` (✨ Generated from Field `Order`.`totalAmount` of type `Float!`)
  """
  totalAmount_expr: Float_Expr @fdc_forbiddenInVariables
  """
  ✨ `_update` server value variant of `totalAmount` (✨ Generated from Field `Order`.`totalAmount` of type `Float!`)
  """
  totalAmount_update: [Float_Update!] @fdc_forbiddenInVariables
}
"""
✨ Generated filter input type for table 'Order'. This input allows filtering objects using various conditions. Use `_or`, `_and`, and `_not` to compose complex filters.
"""
input Order_Filter {
  """
  Apply multiple filter conditions using `AND` logic.
  """
  _and: [Order_Filter!]
  """
  Negate the result of the provided filter condition.
  """
  _not: Order_Filter
  """
  Apply multiple filter conditions using `OR` logic.
  """
  _or: [Order_Filter!]
  """
  ✨ Generated from Field `Order`.`id` of type `UUID!`
  """
  id: UUID_Filter
  """
  ✨ Generated from Field `Order`.`buyerId` of type `UUID!`
  """
  buyerId: UUID_Filter
  """
  ✨ Generated from Field `Order`.`listingId` of type `UUID!`
  """
  listingId: UUID_Filter
  """
  ✨ Generated from Field `Order`.`buyer` of type `User!`
  """
  buyer: User_Filter
  """
  ✨ Generated from Field `Order`.`listing` of type `HarvestListing!`
  """
  listing: HarvestListing_Filter
  """
  ✨ Generated from Field `Order`.`quantity` of type `Int!`
  """
  quantity: Int_Filter
  """
  ✨ Generated from Field `Order`.`status` of type `String!`
  """
  status: String_Filter
  """
  ✨ Generated from Field `Order`.`totalAmount` of type `Float!`
  """
  totalAmount: Float_Filter
}
"""
✨ Generated first-row input type for table 'Order'. This input selects the first row matching the filter criteria, ordered according to the specified conditions.
"""
input Order_FirstRow {
  """
  Order the result by the specified fields.
  """
  orderBy: [Order_Order!]
  """
  Filters rows based on the specified conditions.
  """
  where: Order_Filter
}
"""
✨ Generated having input type for table 'Order'. This input allows you to filter groups during aggregate queries using various conditions. Use `_or`, `_and`, and `_not` to compose complex filters.
"""
input Order_Having {
  """
  Apply multiple Having conditions using `AND` logic.
  """
  _and: [Order_Having!]
  """
  Whether to apply DISTINCT to the aggregate function.
  """
  _distinct: Boolean
  """
  Negate the result of the provided Having condition.
  """
  _not: Order_Having
  """
  Apply multiple Having conditions using `OR` logic.
  """
  _or: [Order_Having!]
  """
  ✨ Generated from Field `Order`.`_count` of type `Int!`
  """
  _count: Int_Filter
  """
  ✨ Generated from Field `Order`.`buyerId_count` of type `Int!`
  """
  buyerId_count: Int_Filter
  """
  ✨ Generated from Field `Order`.`id_count` of type `Int!`
  """
  id_count: Int_Filter
  """
  ✨ Generated from Field `Order`.`listingId_count` of type `Int!`
  """
  listingId_count: Int_Filter
  """
  ✨ Generated from Field `Order`.`quantity_count` of type `Int!`
  """
  quantity_count: Int_Filter
  """
  ✨ Generated from Field `Order`.`status_count` of type `Int!`
  """
  status_count: Int_Filter
  """
  ✨ Generated from Field `Order`.`totalAmount_count` of type `Int!`
  """
  totalAmount_count: Int_Filter
  """
  ✨ Generated from Field `Order`.`quantity_sum` of type `Int`
  """
  quantity_sum: Int_Filter
  """
  ✨ Generated from Field `Order`.`totalAmount_sum` of type `Float`
  """
  totalAmount_sum: Float_Filter
  """
  ✨ Generated from Field `Order`.`quantity_avg` of type `Float`
  """
  quantity_avg: Float_Filter
  """
  ✨ Generated from Field `Order`.`totalAmount_avg` of type `Float`
  """
  totalAmount_avg: Float_Filter
  """
  ✨ Generated from Field `Order`.`quantity_min` of type `Int`
  """
  quantity_min: Int_Filter
  """
  ✨ Generated from Field `Order`.`totalAmount_min` of type `Float`
  """
  totalAmount_min: Float_Filter
  """
  ✨ Generated from Field `Order`.`quantity_max` of type `Int`
  """
  quantity_max: Int_Filter
  """
  ✨ Generated from Field `Order`.`totalAmount_max` of type `Float`
  """
  totalAmount_max: Float_Filter
}
"""
✨ Generated key input type for table 'Order'. It represents the primary key fields used to uniquely identify a row in the table.
"""
input Order_Key {
  """
  ✨ Generated from Field `Order`.`id` of type `UUID!`
  """
  id: UUID
  """
  ✨ `_expr` server value variant of `id` (✨ Generated from Field `Order`.`id` of type `UUID!`)
  """
  id_expr: UUID_Expr @fdc_forbiddenInVariables
}
"""
✨ Generated list filter input type for table 'Order'. This input applies filtering logic based on the count or existence of related objects that matches certain criteria.
"""
input Order_ListFilter {
  """
  The desired number of objects that match the condition (defaults to at least one).
  """
  count: Int_Filter = {gt:0}
  """
  Condition of the related objects to filter for.
  """
  exist: Order_Filter
}
"""
✨ Generated order input type for table 'Order'. This input defines the sorting order of rows in query results based on one or more fields.
"""
input Order_Order {
  """
  ✨ Generated from Field `Order`.`id` of type `UUID!`
  """
  id: OrderDirection
  """
  ✨ Generated from Field `Order`.`buyerId` of type `UUID!`
  """
  buyerId: OrderDirection
  """
  ✨ Generated from Field `Order`.`listingId` of type `UUID!`
  """
  listingId: OrderDirection
  """
  ✨ Generated from Field `Order`.`buyer` of type `User!`
  """
  buyer: User_Order
  """
  ✨ Generated from Field `Order`.`listing` of type `HarvestListing!`
  """
  listing: HarvestListing_Order
  """
  ✨ Generated from Field `Order`.`quantity` of type `Int!`
  """
  quantity: OrderDirection
  """
  ✨ Generated from Field `Order`.`status` of type `String!`
  """
  status: OrderDirection
  """
  ✨ Generated from Field `Order`.`totalAmount` of type `Float!`
  """
  totalAmount: OrderDirection
  """
  ✨ Generated from Field `Order`.`_count` of type `Int!`
  """
  _count: OrderDirection
  """
  ✨ Generated from Field `Order`.`buyerId_count` of type `Int!`
  """
  buyerId_count: OrderDirection
  """
  ✨ Generated from Field `Order`.`id_count` of type `Int!`
  """
  id_count: OrderDirection
  """
  ✨ Generated from Field `Order`.`listingId_count` of type `Int!`
  """
  listingId_count: OrderDirection
  """
  ✨ Generated from Field `Order`.`quantity_count` of type `Int!`
  """
  quantity_count: OrderDirection
  """
  ✨ Generated from Field `Order`.`status_count` of type `Int!`
  """
  status_count: OrderDirection
  """
  ✨ Generated from Field `Order`.`totalAmount_count` of type `Int!`
  """
  totalAmount_count: OrderDirection
  """
  ✨ Generated from Field `Order`.`quantity_sum` of type `Int`
  """
  quantity_sum: OrderDirection
  """
  ✨ Generated from Field `Order`.`totalAmount_sum` of type `Float`
  """
  totalAmount_sum: OrderDirection
  """
  ✨ Generated from Field `Order`.`quantity_avg` of type `Float`
  """
  quantity_avg: OrderDirection
  """
  ✨ Generated from Field `Order`.`totalAmount_avg` of type `Float`
  """
  totalAmount_avg: OrderDirection
  """
  ✨ Generated from Field `Order`.`quantity_min` of type `Int`
  """
  quantity_min: OrderDirection
  """
  ✨ Generated from Field `Order`.`totalAmount_min` of type `Float`
  """
  totalAmount_min: OrderDirection
  """
  ✨ Generated from Field `Order`.`quantity_max` of type `Int`
  """
  quantity_max: OrderDirection
  """
  ✨ Generated from Field `Order`.`totalAmount_max` of type `Float`
  """
  totalAmount_max: OrderDirection
}
"""
✨ Generated data input type for table 'Pond'. It includes all necessary fields for creating or upserting rows into table.
"""
input Pond_Data {
  """
  ✨ Generated from Field `Pond`.`id` of type `UUID!`
  """
  id: UUID
  """
  ✨ `_expr` server value variant of `id` (✨ Generated from Field `Pond`.`id` of type `UUID!`)
  """
  id_expr: UUID_Expr @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `Pond`.`farmerId` of type `UUID!`
  """
  farmerId: UUID
  """
  ✨ `_expr` server value variant of `farmerId` (✨ Generated from Field `Pond`.`farmerId` of type `UUID!`)
  """
  farmerId_expr: UUID_Expr @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `Pond`.`farmer` of type `User!`
  """
  farmer: User_Key @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `Pond`.`capacity` of type `Float`
  """
  capacity: Float
  """
  ✨ `_expr` server value variant of `capacity` (✨ Generated from Field `Pond`.`capacity` of type `Float`)
  """
  capacity_expr: Float_Expr @fdc_forbiddenInVariables
  """
  ✨ `_update` server value variant of `capacity` (✨ Generated from Field `Pond`.`capacity` of type `Float`)
  """
  capacity_update: [Float_Update!] @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `Pond`.`dimensions` of type `String`
  """
  dimensions: String
  """
  ✨ `_expr` server value variant of `dimensions` (✨ Generated from Field `Pond`.`dimensions` of type `String`)
  """
  dimensions_expr: String_Expr @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `Pond`.`location` of type `String!`
  """
  location: String
  """
  ✨ `_expr` server value variant of `location` (✨ Generated from Field `Pond`.`location` of type `String!`)
  """
  location_expr: String_Expr @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `Pond`.`name` of type `String!`
  """
  name: String
  """
  ✨ `_expr` server value variant of `name` (✨ Generated from Field `Pond`.`name` of type `String!`)
  """
  name_expr: String_Expr @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `Pond`.`sensorReadings_on_pond` of type `[SensorReading!]!`
  """
  sensorReadings_on_pond: [SensorReading_Data!]
  """
  ✨ Generated from Field `Pond`.`smartRecommendations_on_pond` of type `[SmartRecommendation!]!`
  """
  smartRecommendations_on_pond: [SmartRecommendation_Data!]
}
"""
✨ Generated filter input type for table 'Pond'. This input allows filtering objects using various conditions. Use `_or`, `_and`, and `_not` to compose complex filters.
"""
input Pond_Filter {
  """
  Apply multiple filter conditions using `AND` logic.
  """
  _and: [Pond_Filter!]
  """
  Negate the result of the provided filter condition.
  """
  _not: Pond_Filter
  """
  Apply multiple filter conditions using `OR` logic.
  """
  _or: [Pond_Filter!]
  """
  ✨ Generated from Field `Pond`.`id` of type `UUID!`
  """
  id: UUID_Filter
  """
  ✨ Generated from Field `Pond`.`farmerId` of type `UUID!`
  """
  farmerId: UUID_Filter
  """
  ✨ Generated from Field `Pond`.`farmer` of type `User!`
  """
  farmer: User_Filter
  """
  ✨ Generated from Field `Pond`.`capacity` of type `Float`
  """
  capacity: Float_Filter
  """
  ✨ Generated from Field `Pond`.`dimensions` of type `String`
  """
  dimensions: String_Filter
  """
  ✨ Generated from Field `Pond`.`location` of type `String!`
  """
  location: String_Filter
  """
  ✨ Generated from Field `Pond`.`name` of type `String!`
  """
  name: String_Filter
  """
  ✨ Generated from Field `Pond`.`sensorReadings_on_pond` of type `[SensorReading!]!`
  """
  sensorReadings_on_pond: SensorReading_ListFilter
  """
  ✨ Generated from Field `Pond`.`smartRecommendations_on_pond` of type `[SmartRecommendation!]!`
  """
  smartRecommendations_on_pond: SmartRecommendation_ListFilter
}
"""
✨ Generated first-row input type for table 'Pond'. This input selects the first row matching the filter criteria, ordered according to the specified conditions.
"""
input Pond_FirstRow {
  """
  Order the result by the specified fields.
  """
  orderBy: [Pond_Order!]
  """
  Filters rows based on the specified conditions.
  """
  where: Pond_Filter
}
"""
✨ Generated having input type for table 'Pond'. This input allows you to filter groups during aggregate queries using various conditions. Use `_or`, `_and`, and `_not` to compose complex filters.
"""
input Pond_Having {
  """
  Apply multiple Having conditions using `AND` logic.
  """
  _and: [Pond_Having!]
  """
  Whether to apply DISTINCT to the aggregate function.
  """
  _distinct: Boolean
  """
  Negate the result of the provided Having condition.
  """
  _not: Pond_Having
  """
  Apply multiple Having conditions using `OR` logic.
  """
  _or: [Pond_Having!]
  """
  ✨ Generated from Field `Pond`.`_count` of type `Int!`
  """
  _count: Int_Filter
  """
  ✨ Generated from Field `Pond`.`capacity_count` of type `Int!`
  """
  capacity_count: Int_Filter
  """
  ✨ Generated from Field `Pond`.`dimensions_count` of type `Int!`
  """
  dimensions_count: Int_Filter
  """
  ✨ Generated from Field `Pond`.`farmerId_count` of type `Int!`
  """
  farmerId_count: Int_Filter
  """
  ✨ Generated from Field `Pond`.`id_count` of type `Int!`
  """
  id_count: Int_Filter
  """
  ✨ Generated from Field `Pond`.`location_count` of type `Int!`
  """
  location_count: Int_Filter
  """
  ✨ Generated from Field `Pond`.`name_count` of type `Int!`
  """
  name_count: Int_Filter
  """
  ✨ Generated from Field `Pond`.`capacity_sum` of type `Float`
  """
  capacity_sum: Float_Filter
  """
  ✨ Generated from Field `Pond`.`capacity_avg` of type `Float`
  """
  capacity_avg: Float_Filter
  """
  ✨ Generated from Field `Pond`.`capacity_min` of type `Float`
  """
  capacity_min: Float_Filter
  """
  ✨ Generated from Field `Pond`.`capacity_max` of type `Float`
  """
  capacity_max: Float_Filter
}
"""
✨ Generated key input type for table 'Pond'. It represents the primary key fields used to uniquely identify a row in the table.
"""
input Pond_Key {
  """
  ✨ Generated from Field `Pond`.`id` of type `UUID!`
  """
  id: UUID
  """
  ✨ `_expr` server value variant of `id` (✨ Generated from Field `Pond`.`id` of type `UUID!`)
  """
  id_expr: UUID_Expr @fdc_forbiddenInVariables
}
"""
✨ Generated list filter input type for table 'Pond'. This input applies filtering logic based on the count or existence of related objects that matches certain criteria.
"""
input Pond_ListFilter {
  """
  The desired number of objects that match the condition (defaults to at least one).
  """
  count: Int_Filter = {gt:0}
  """
  Condition of the related objects to filter for.
  """
  exist: Pond_Filter
}
"""
✨ Generated order input type for table 'Pond'. This input defines the sorting order of rows in query results based on one or more fields.
"""
input Pond_Order {
  """
  ✨ Generated from Field `Pond`.`id` of type `UUID!`
  """
  id: OrderDirection
  """
  ✨ Generated from Field `Pond`.`farmerId` of type `UUID!`
  """
  farmerId: OrderDirection
  """
  ✨ Generated from Field `Pond`.`farmer` of type `User!`
  """
  farmer: User_Order
  """
  ✨ Generated from Field `Pond`.`capacity` of type `Float`
  """
  capacity: OrderDirection
  """
  ✨ Generated from Field `Pond`.`dimensions` of type `String`
  """
  dimensions: OrderDirection
  """
  ✨ Generated from Field `Pond`.`location` of type `String!`
  """
  location: OrderDirection
  """
  ✨ Generated from Field `Pond`.`name` of type `String!`
  """
  name: OrderDirection
  """
  ✨ Generated from Field `Pond`.`_count` of type `Int!`
  """
  _count: OrderDirection
  """
  ✨ Generated from Field `Pond`.`capacity_count` of type `Int!`
  """
  capacity_count: OrderDirection
  """
  ✨ Generated from Field `Pond`.`dimensions_count` of type `Int!`
  """
  dimensions_count: OrderDirection
  """
  ✨ Generated from Field `Pond`.`farmerId_count` of type `Int!`
  """
  farmerId_count: OrderDirection
  """
  ✨ Generated from Field `Pond`.`id_count` of type `Int!`
  """
  id_count: OrderDirection
  """
  ✨ Generated from Field `Pond`.`location_count` of type `Int!`
  """
  location_count: OrderDirection
  """
  ✨ Generated from Field `Pond`.`name_count` of type `Int!`
  """
  name_count: OrderDirection
  """
  ✨ Generated from Field `Pond`.`capacity_sum` of type `Float`
  """
  capacity_sum: OrderDirection
  """
  ✨ Generated from Field `Pond`.`capacity_avg` of type `Float`
  """
  capacity_avg: OrderDirection
  """
  ✨ Generated from Field `Pond`.`capacity_min` of type `Float`
  """
  capacity_min: OrderDirection
  """
  ✨ Generated from Field `Pond`.`capacity_max` of type `Float`
  """
  capacity_max: OrderDirection
}
"""
✨ Generated data input type for table 'SensorReading'. It includes all necessary fields for creating or upserting rows into table.
"""
input SensorReading_Data {
  """
  ✨ Generated from Field `SensorReading`.`id` of type `UUID!`
  """
  id: UUID
  """
  ✨ `_expr` server value variant of `id` (✨ Generated from Field `SensorReading`.`id` of type `UUID!`)
  """
  id_expr: UUID_Expr @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `SensorReading`.`pondId` of type `UUID!`
  """
  pondId: UUID
  """
  ✨ `_expr` server value variant of `pondId` (✨ Generated from Field `SensorReading`.`pondId` of type `UUID!`)
  """
  pondId_expr: UUID_Expr @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `SensorReading`.`pond` of type `Pond!`
  """
  pond: Pond_Key @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `SensorReading`.`ammonia` of type `Float!`
  """
  ammonia: Float
  """
  ✨ `_expr` server value variant of `ammonia` (✨ Generated from Field `SensorReading`.`ammonia` of type `Float!`)
  """
  ammonia_expr: Float_Expr @fdc_forbiddenInVariables
  """
  ✨ `_update` server value variant of `ammonia` (✨ Generated from Field `SensorReading`.`ammonia` of type `Float!`)
  """
  ammonia_update: [Float_Update!] @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `SensorReading`.`dissolvedOxygen` of type `Float!`
  """
  dissolvedOxygen: Float
  """
  ✨ `_expr` server value variant of `dissolvedOxygen` (✨ Generated from Field `SensorReading`.`dissolvedOxygen` of type `Float!`)
  """
  dissolvedOxygen_expr: Float_Expr @fdc_forbiddenInVariables
  """
  ✨ `_update` server value variant of `dissolvedOxygen` (✨ Generated from Field `SensorReading`.`dissolvedOxygen` of type `Float!`)
  """
  dissolvedOxygen_update: [Float_Update!] @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `SensorReading`.`ph` of type `Float!`
  """
  ph: Float
  """
  ✨ `_expr` server value variant of `ph` (✨ Generated from Field `SensorReading`.`ph` of type `Float!`)
  """
  ph_expr: Float_Expr @fdc_forbiddenInVariables
  """
  ✨ `_update` server value variant of `ph` (✨ Generated from Field `SensorReading`.`ph` of type `Float!`)
  """
  ph_update: [Float_Update!] @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `SensorReading`.`temperature` of type `Float!`
  """
  temperature: Float
  """
  ✨ `_expr` server value variant of `temperature` (✨ Generated from Field `SensorReading`.`temperature` of type `Float!`)
  """
  temperature_expr: Float_Expr @fdc_forbiddenInVariables
  """
  ✨ `_update` server value variant of `temperature` (✨ Generated from Field `SensorReading`.`temperature` of type `Float!`)
  """
  temperature_update: [Float_Update!] @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `SensorReading`.`timestamp` of type `Timestamp!`
  """
  timestamp: Timestamp
  """
  ✨ `_expr` server value variant of `timestamp` (✨ Generated from Field `SensorReading`.`timestamp` of type `Timestamp!`)
  """
  timestamp_expr: Timestamp_Expr @fdc_forbiddenInVariables
  """
  ✨ `_time` server value variant of `timestamp` (✨ Generated from Field `SensorReading`.`timestamp` of type `Timestamp!`)
  """
  timestamp_time: Timestamp_Relative @fdc_forbiddenInVariables
  """
  ✨ `_update` server value variant of `timestamp` (✨ Generated from Field `SensorReading`.`timestamp` of type `Timestamp!`)
  """
  timestamp_update: [Timestamp_Update!] @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `SensorReading`.`turbidity` of type `Float!`
  """
  turbidity: Float
  """
  ✨ `_expr` server value variant of `turbidity` (✨ Generated from Field `SensorReading`.`turbidity` of type `Float!`)
  """
  turbidity_expr: Float_Expr @fdc_forbiddenInVariables
  """
  ✨ `_update` server value variant of `turbidity` (✨ Generated from Field `SensorReading`.`turbidity` of type `Float!`)
  """
  turbidity_update: [Float_Update!] @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `SensorReading`.`smartRecommendations_on_sensorReading` of type `[SmartRecommendation!]!`
  """
  smartRecommendations_on_sensorReading: [SmartRecommendation_Data!]
}
"""
✨ Generated filter input type for table 'SensorReading'. This input allows filtering objects using various conditions. Use `_or`, `_and`, and `_not` to compose complex filters.
"""
input SensorReading_Filter {
  """
  Apply multiple filter conditions using `AND` logic.
  """
  _and: [SensorReading_Filter!]
  """
  Negate the result of the provided filter condition.
  """
  _not: SensorReading_Filter
  """
  Apply multiple filter conditions using `OR` logic.
  """
  _or: [SensorReading_Filter!]
  """
  ✨ Generated from Field `SensorReading`.`id` of type `UUID!`
  """
  id: UUID_Filter
  """
  ✨ Generated from Field `SensorReading`.`pondId` of type `UUID!`
  """
  pondId: UUID_Filter
  """
  ✨ Generated from Field `SensorReading`.`pond` of type `Pond!`
  """
  pond: Pond_Filter
  """
  ✨ Generated from Field `SensorReading`.`ammonia` of type `Float!`
  """
  ammonia: Float_Filter
  """
  ✨ Generated from Field `SensorReading`.`dissolvedOxygen` of type `Float!`
  """
  dissolvedOxygen: Float_Filter
  """
  ✨ Generated from Field `SensorReading`.`ph` of type `Float!`
  """
  ph: Float_Filter
  """
  ✨ Generated from Field `SensorReading`.`temperature` of type `Float!`
  """
  temperature: Float_Filter
  """
  ✨ Generated from Field `SensorReading`.`timestamp` of type `Timestamp!`
  """
  timestamp: Timestamp_Filter
  """
  ✨ Generated from Field `SensorReading`.`turbidity` of type `Float!`
  """
  turbidity: Float_Filter
  """
  ✨ Generated from Field `SensorReading`.`smartRecommendations_on_sensorReading` of type `[SmartRecommendation!]!`
  """
  smartRecommendations_on_sensorReading: SmartRecommendation_ListFilter
}
"""
✨ Generated first-row input type for table 'SensorReading'. This input selects the first row matching the filter criteria, ordered according to the specified conditions.
"""
input SensorReading_FirstRow {
  """
  Order the result by the specified fields.
  """
  orderBy: [SensorReading_Order!]
  """
  Filters rows based on the specified conditions.
  """
  where: SensorReading_Filter
}
"""
✨ Generated having input type for table 'SensorReading'. This input allows you to filter groups during aggregate queries using various conditions. Use `_or`, `_and`, and `_not` to compose complex filters.
"""
input SensorReading_Having {
  """
  Apply multiple Having conditions using `AND` logic.
  """
  _and: [SensorReading_Having!]
  """
  Whether to apply DISTINCT to the aggregate function.
  """
  _distinct: Boolean
  """
  Negate the result of the provided Having condition.
  """
  _not: SensorReading_Having
  """
  Apply multiple Having conditions using `OR` logic.
  """
  _or: [SensorReading_Having!]
  """
  ✨ Generated from Field `SensorReading`.`_count` of type `Int!`
  """
  _count: Int_Filter
  """
  ✨ Generated from Field `SensorReading`.`ammonia_count` of type `Int!`
  """
  ammonia_count: Int_Filter
  """
  ✨ Generated from Field `SensorReading`.`dissolvedOxygen_count` of type `Int!`
  """
  dissolvedOxygen_count: Int_Filter
  """
  ✨ Generated from Field `SensorReading`.`id_count` of type `Int!`
  """
  id_count: Int_Filter
  """
  ✨ Generated from Field `SensorReading`.`ph_count` of type `Int!`
  """
  ph_count: Int_Filter
  """
  ✨ Generated from Field `SensorReading`.`pondId_count` of type `Int!`
  """
  pondId_count: Int_Filter
  """
  ✨ Generated from Field `SensorReading`.`temperature_count` of type `Int!`
  """
  temperature_count: Int_Filter
  """
  ✨ Generated from Field `SensorReading`.`timestamp_count` of type `Int!`
  """
  timestamp_count: Int_Filter
  """
  ✨ Generated from Field `SensorReading`.`turbidity_count` of type `Int!`
  """
  turbidity_count: Int_Filter
  """
  ✨ Generated from Field `SensorReading`.`ammonia_sum` of type `Float`
  """
  ammonia_sum: Float_Filter
  """
  ✨ Generated from Field `SensorReading`.`dissolvedOxygen_sum` of type `Float`
  """
  dissolvedOxygen_sum: Float_Filter
  """
  ✨ Generated from Field `SensorReading`.`ph_sum` of type `Float`
  """
  ph_sum: Float_Filter
  """
  ✨ Generated from Field `SensorReading`.`temperature_sum` of type `Float`
  """
  temperature_sum: Float_Filter
  """
  ✨ Generated from Field `SensorReading`.`turbidity_sum` of type `Float`
  """
  turbidity_sum: Float_Filter
  """
  ✨ Generated from Field `SensorReading`.`ammonia_avg` of type `Float`
  """
  ammonia_avg: Float_Filter
  """
  ✨ Generated from Field `SensorReading`.`dissolvedOxygen_avg` of type `Float`
  """
  dissolvedOxygen_avg: Float_Filter
  """
  ✨ Generated from Field `SensorReading`.`ph_avg` of type `Float`
  """
  ph_avg: Float_Filter
  """
  ✨ Generated from Field `SensorReading`.`temperature_avg` of type `Float`
  """
  temperature_avg: Float_Filter
  """
  ✨ Generated from Field `SensorReading`.`turbidity_avg` of type `Float`
  """
  turbidity_avg: Float_Filter
  """
  ✨ Generated from Field `SensorReading`.`ammonia_min` of type `Float`
  """
  ammonia_min: Float_Filter
  """
  ✨ Generated from Field `SensorReading`.`dissolvedOxygen_min` of type `Float`
  """
  dissolvedOxygen_min: Float_Filter
  """
  ✨ Generated from Field `SensorReading`.`ph_min` of type `Float`
  """
  ph_min: Float_Filter
  """
  ✨ Generated from Field `SensorReading`.`temperature_min` of type `Float`
  """
  temperature_min: Float_Filter
  """
  ✨ Generated from Field `SensorReading`.`timestamp_min` of type `Timestamp`
  """
  timestamp_min: Timestamp_Filter
  """
  ✨ Generated from Field `SensorReading`.`turbidity_min` of type `Float`
  """
  turbidity_min: Float_Filter
  """
  ✨ Generated from Field `SensorReading`.`ammonia_max` of type `Float`
  """
  ammonia_max: Float_Filter
  """
  ✨ Generated from Field `SensorReading`.`dissolvedOxygen_max` of type `Float`
  """
  dissolvedOxygen_max: Float_Filter
  """
  ✨ Generated from Field `SensorReading`.`ph_max` of type `Float`
  """
  ph_max: Float_Filter
  """
  ✨ Generated from Field `SensorReading`.`temperature_max` of type `Float`
  """
  temperature_max: Float_Filter
  """
  ✨ Generated from Field `SensorReading`.`timestamp_max` of type `Timestamp`
  """
  timestamp_max: Timestamp_Filter
  """
  ✨ Generated from Field `SensorReading`.`turbidity_max` of type `Float`
  """
  turbidity_max: Float_Filter
}
"""
✨ Generated key input type for table 'SensorReading'. It represents the primary key fields used to uniquely identify a row in the table.
"""
input SensorReading_Key {
  """
  ✨ Generated from Field `SensorReading`.`id` of type `UUID!`
  """
  id: UUID
  """
  ✨ `_expr` server value variant of `id` (✨ Generated from Field `SensorReading`.`id` of type `UUID!`)
  """
  id_expr: UUID_Expr @fdc_forbiddenInVariables
}
"""
✨ Generated list filter input type for table 'SensorReading'. This input applies filtering logic based on the count or existence of related objects that matches certain criteria.
"""
input SensorReading_ListFilter {
  """
  The desired number of objects that match the condition (defaults to at least one).
  """
  count: Int_Filter = {gt:0}
  """
  Condition of the related objects to filter for.
  """
  exist: SensorReading_Filter
}
"""
✨ Generated order input type for table 'SensorReading'. This input defines the sorting order of rows in query results based on one or more fields.
"""
input SensorReading_Order {
  """
  ✨ Generated from Field `SensorReading`.`id` of type `UUID!`
  """
  id: OrderDirection
  """
  ✨ Generated from Field `SensorReading`.`pondId` of type `UUID!`
  """
  pondId: OrderDirection
  """
  ✨ Generated from Field `SensorReading`.`pond` of type `Pond!`
  """
  pond: Pond_Order
  """
  ✨ Generated from Field `SensorReading`.`ammonia` of type `Float!`
  """
  ammonia: OrderDirection
  """
  ✨ Generated from Field `SensorReading`.`dissolvedOxygen` of type `Float!`
  """
  dissolvedOxygen: OrderDirection
  """
  ✨ Generated from Field `SensorReading`.`ph` of type `Float!`
  """
  ph: OrderDirection
  """
  ✨ Generated from Field `SensorReading`.`temperature` of type `Float!`
  """
  temperature: OrderDirection
  """
  ✨ Generated from Field `SensorReading`.`timestamp` of type `Timestamp!`
  """
  timestamp: OrderDirection
  """
  ✨ Generated from Field `SensorReading`.`turbidity` of type `Float!`
  """
  turbidity: OrderDirection
  """
  ✨ Generated from Field `SensorReading`.`_count` of type `Int!`
  """
  _count: OrderDirection
  """
  ✨ Generated from Field `SensorReading`.`ammonia_count` of type `Int!`
  """
  ammonia_count: OrderDirection
  """
  ✨ Generated from Field `SensorReading`.`dissolvedOxygen_count` of type `Int!`
  """
  dissolvedOxygen_count: OrderDirection
  """
  ✨ Generated from Field `SensorReading`.`id_count` of type `Int!`
  """
  id_count: OrderDirection
  """
  ✨ Generated from Field `SensorReading`.`ph_count` of type `Int!`
  """
  ph_count: OrderDirection
  """
  ✨ Generated from Field `SensorReading`.`pondId_count` of type `Int!`
  """
  pondId_count: OrderDirection
  """
  ✨ Generated from Field `SensorReading`.`temperature_count` of type `Int!`
  """
  temperature_count: OrderDirection
  """
  ✨ Generated from Field `SensorReading`.`timestamp_count` of type `Int!`
  """
  timestamp_count: OrderDirection
  """
  ✨ Generated from Field `SensorReading`.`turbidity_count` of type `Int!`
  """
  turbidity_count: OrderDirection
  """
  ✨ Generated from Field `SensorReading`.`ammonia_sum` of type `Float`
  """
  ammonia_sum: OrderDirection
  """
  ✨ Generated from Field `SensorReading`.`dissolvedOxygen_sum` of type `Float`
  """
  dissolvedOxygen_sum: OrderDirection
  """
  ✨ Generated from Field `SensorReading`.`ph_sum` of type `Float`
  """
  ph_sum: OrderDirection
  """
  ✨ Generated from Field `SensorReading`.`temperature_sum` of type `Float`
  """
  temperature_sum: OrderDirection
  """
  ✨ Generated from Field `SensorReading`.`turbidity_sum` of type `Float`
  """
  turbidity_sum: OrderDirection
  """
  ✨ Generated from Field `SensorReading`.`ammonia_avg` of type `Float`
  """
  ammonia_avg: OrderDirection
  """
  ✨ Generated from Field `SensorReading`.`dissolvedOxygen_avg` of type `Float`
  """
  dissolvedOxygen_avg: OrderDirection
  """
  ✨ Generated from Field `SensorReading`.`ph_avg` of type `Float`
  """
  ph_avg: OrderDirection
  """
  ✨ Generated from Field `SensorReading`.`temperature_avg` of type `Float`
  """
  temperature_avg: OrderDirection
  """
  ✨ Generated from Field `SensorReading`.`turbidity_avg` of type `Float`
  """
  turbidity_avg: OrderDirection
  """
  ✨ Generated from Field `SensorReading`.`ammonia_min` of type `Float`
  """
  ammonia_min: OrderDirection
  """
  ✨ Generated from Field `SensorReading`.`dissolvedOxygen_min` of type `Float`
  """
  dissolvedOxygen_min: OrderDirection
  """
  ✨ Generated from Field `SensorReading`.`ph_min` of type `Float`
  """
  ph_min: OrderDirection
  """
  ✨ Generated from Field `SensorReading`.`temperature_min` of type `Float`
  """
  temperature_min: OrderDirection
  """
  ✨ Generated from Field `SensorReading`.`timestamp_min` of type `Timestamp`
  """
  timestamp_min: OrderDirection
  """
  ✨ Generated from Field `SensorReading`.`turbidity_min` of type `Float`
  """
  turbidity_min: OrderDirection
  """
  ✨ Generated from Field `SensorReading`.`ammonia_max` of type `Float`
  """
  ammonia_max: OrderDirection
  """
  ✨ Generated from Field `SensorReading`.`dissolvedOxygen_max` of type `Float`
  """
  dissolvedOxygen_max: OrderDirection
  """
  ✨ Generated from Field `SensorReading`.`ph_max` of type `Float`
  """
  ph_max: OrderDirection
  """
  ✨ Generated from Field `SensorReading`.`temperature_max` of type `Float`
  """
  temperature_max: OrderDirection
  """
  ✨ Generated from Field `SensorReading`.`timestamp_max` of type `Timestamp`
  """
  timestamp_max: OrderDirection
  """
  ✨ Generated from Field `SensorReading`.`turbidity_max` of type `Float`
  """
  turbidity_max: OrderDirection
}
"""
✨ Generated data input type for table 'SmartRecommendation'. It includes all necessary fields for creating or upserting rows into table.
"""
input SmartRecommendation_Data {
  """
  ✨ Generated from Field `SmartRecommendation`.`id` of type `UUID!`
  """
  id: UUID
  """
  ✨ `_expr` server value variant of `id` (✨ Generated from Field `SmartRecommendation`.`id` of type `UUID!`)
  """
  id_expr: UUID_Expr @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `SmartRecommendation`.`pondId` of type `UUID!`
  """
  pondId: UUID
  """
  ✨ `_expr` server value variant of `pondId` (✨ Generated from Field `SmartRecommendation`.`pondId` of type `UUID!`)
  """
  pondId_expr: UUID_Expr @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `SmartRecommendation`.`sensorReadingId` of type `UUID`
  """
  sensorReadingId: UUID
  """
  ✨ `_expr` server value variant of `sensorReadingId` (✨ Generated from Field `SmartRecommendation`.`sensorReadingId` of type `UUID`)
  """
  sensorReadingId_expr: UUID_Expr @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `SmartRecommendation`.`pond` of type `Pond!`
  """
  pond: Pond_Key @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `SmartRecommendation`.`sensorReading` of type `SensorReading`
  """
  sensorReading: SensorReading_Key @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `SmartRecommendation`.`message` of type `String!`
  """
  message: String
  """
  ✨ `_expr` server value variant of `message` (✨ Generated from Field `SmartRecommendation`.`message` of type `String!`)
  """
  message_expr: String_Expr @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `SmartRecommendation`.`priority` of type `String!`
  """
  priority: String
  """
  ✨ `_expr` server value variant of `priority` (✨ Generated from Field `SmartRecommendation`.`priority` of type `String!`)
  """
  priority_expr: String_Expr @fdc_forbiddenInVariables
}
"""
✨ Generated filter input type for table 'SmartRecommendation'. This input allows filtering objects using various conditions. Use `_or`, `_and`, and `_not` to compose complex filters.
"""
input SmartRecommendation_Filter {
  """
  Apply multiple filter conditions using `AND` logic.
  """
  _and: [SmartRecommendation_Filter!]
  """
  Negate the result of the provided filter condition.
  """
  _not: SmartRecommendation_Filter
  """
  Apply multiple filter conditions using `OR` logic.
  """
  _or: [SmartRecommendation_Filter!]
  """
  ✨ Generated from Field `SmartRecommendation`.`id` of type `UUID!`
  """
  id: UUID_Filter
  """
  ✨ Generated from Field `SmartRecommendation`.`pondId` of type `UUID!`
  """
  pondId: UUID_Filter
  """
  ✨ Generated from Field `SmartRecommendation`.`sensorReadingId` of type `UUID`
  """
  sensorReadingId: UUID_Filter
  """
  ✨ Generated from Field `SmartRecommendation`.`pond` of type `Pond!`
  """
  pond: Pond_Filter
  """
  ✨ Generated from Field `SmartRecommendation`.`sensorReading` of type `SensorReading`
  """
  sensorReading: SensorReading_Filter
  """
  ✨ Generated from Field `SmartRecommendation`.`message` of type `String!`
  """
  message: String_Filter
  """
  ✨ Generated from Field `SmartRecommendation`.`priority` of type `String!`
  """
  priority: String_Filter
}
"""
✨ Generated first-row input type for table 'SmartRecommendation'. This input selects the first row matching the filter criteria, ordered according to the specified conditions.
"""
input SmartRecommendation_FirstRow {
  """
  Order the result by the specified fields.
  """
  orderBy: [SmartRecommendation_Order!]
  """
  Filters rows based on the specified conditions.
  """
  where: SmartRecommendation_Filter
}
"""
✨ Generated having input type for table 'SmartRecommendation'. This input allows you to filter groups during aggregate queries using various conditions. Use `_or`, `_and`, and `_not` to compose complex filters.
"""
input SmartRecommendation_Having {
  """
  Apply multiple Having conditions using `AND` logic.
  """
  _and: [SmartRecommendation_Having!]
  """
  Whether to apply DISTINCT to the aggregate function.
  """
  _distinct: Boolean
  """
  Negate the result of the provided Having condition.
  """
  _not: SmartRecommendation_Having
  """
  Apply multiple Having conditions using `OR` logic.
  """
  _or: [SmartRecommendation_Having!]
  """
  ✨ Generated from Field `SmartRecommendation`.`_count` of type `Int!`
  """
  _count: Int_Filter
  """
  ✨ Generated from Field `SmartRecommendation`.`id_count` of type `Int!`
  """
  id_count: Int_Filter
  """
  ✨ Generated from Field `SmartRecommendation`.`message_count` of type `Int!`
  """
  message_count: Int_Filter
  """
  ✨ Generated from Field `SmartRecommendation`.`pondId_count` of type `Int!`
  """
  pondId_count: Int_Filter
  """
  ✨ Generated from Field `SmartRecommendation`.`priority_count` of type `Int!`
  """
  priority_count: Int_Filter
  """
  ✨ Generated from Field `SmartRecommendation`.`sensorReadingId_count` of type `Int!`
  """
  sensorReadingId_count: Int_Filter
}
"""
✨ Generated key input type for table 'SmartRecommendation'. It represents the primary key fields used to uniquely identify a row in the table.
"""
input SmartRecommendation_Key {
  """
  ✨ Generated from Field `SmartRecommendation`.`id` of type `UUID!`
  """
  id: UUID
  """
  ✨ `_expr` server value variant of `id` (✨ Generated from Field `SmartRecommendation`.`id` of type `UUID!`)
  """
  id_expr: UUID_Expr @fdc_forbiddenInVariables
}
"""
✨ Generated list filter input type for table 'SmartRecommendation'. This input applies filtering logic based on the count or existence of related objects that matches certain criteria.
"""
input SmartRecommendation_ListFilter {
  """
  The desired number of objects that match the condition (defaults to at least one).
  """
  count: Int_Filter = {gt:0}
  """
  Condition of the related objects to filter for.
  """
  exist: SmartRecommendation_Filter
}
"""
✨ Generated order input type for table 'SmartRecommendation'. This input defines the sorting order of rows in query results based on one or more fields.
"""
input SmartRecommendation_Order {
  """
  ✨ Generated from Field `SmartRecommendation`.`id` of type `UUID!`
  """
  id: OrderDirection
  """
  ✨ Generated from Field `SmartRecommendation`.`pondId` of type `UUID!`
  """
  pondId: OrderDirection
  """
  ✨ Generated from Field `SmartRecommendation`.`sensorReadingId` of type `UUID`
  """
  sensorReadingId: OrderDirection
  """
  ✨ Generated from Field `SmartRecommendation`.`pond` of type `Pond!`
  """
  pond: Pond_Order
  """
  ✨ Generated from Field `SmartRecommendation`.`sensorReading` of type `SensorReading`
  """
  sensorReading: SensorReading_Order
  """
  ✨ Generated from Field `SmartRecommendation`.`message` of type `String!`
  """
  message: OrderDirection
  """
  ✨ Generated from Field `SmartRecommendation`.`priority` of type `String!`
  """
  priority: OrderDirection
  """
  ✨ Generated from Field `SmartRecommendation`.`_count` of type `Int!`
  """
  _count: OrderDirection
  """
  ✨ Generated from Field `SmartRecommendation`.`id_count` of type `Int!`
  """
  id_count: OrderDirection
  """
  ✨ Generated from Field `SmartRecommendation`.`message_count` of type `Int!`
  """
  message_count: OrderDirection
  """
  ✨ Generated from Field `SmartRecommendation`.`pondId_count` of type `Int!`
  """
  pondId_count: OrderDirection
  """
  ✨ Generated from Field `SmartRecommendation`.`priority_count` of type `Int!`
  """
  priority_count: OrderDirection
  """
  ✨ Generated from Field `SmartRecommendation`.`sensorReadingId_count` of type `Int!`
  """
  sensorReadingId_count: OrderDirection
}
"""
✨ Generated data input type for table 'User'. It includes all necessary fields for creating or upserting rows into table.
"""
input User_Data {
  """
  ✨ Generated from Field `User`.`id` of type `UUID!`
  """
  id: UUID
  """
  ✨ `_expr` server value variant of `id` (✨ Generated from Field `User`.`id` of type `UUID!`)
  """
  id_expr: UUID_Expr @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `User`.`createdAt` of type `Timestamp!`
  """
  createdAt: Timestamp
  """
  ✨ `_expr` server value variant of `createdAt` (✨ Generated from Field `User`.`createdAt` of type `Timestamp!`)
  """
  createdAt_expr: Timestamp_Expr @fdc_forbiddenInVariables
  """
  ✨ `_time` server value variant of `createdAt` (✨ Generated from Field `User`.`createdAt` of type `Timestamp!`)
  """
  createdAt_time: Timestamp_Relative @fdc_forbiddenInVariables
  """
  ✨ `_update` server value variant of `createdAt` (✨ Generated from Field `User`.`createdAt` of type `Timestamp!`)
  """
  createdAt_update: [Timestamp_Update!] @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `User`.`displayName` of type `String`
  """
  displayName: String
  """
  ✨ `_expr` server value variant of `displayName` (✨ Generated from Field `User`.`displayName` of type `String`)
  """
  displayName_expr: String_Expr @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `User`.`email` of type `String!`
  """
  email: String
  """
  ✨ `_expr` server value variant of `email` (✨ Generated from Field `User`.`email` of type `String!`)
  """
  email_expr: String_Expr @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `User`.`phoneNumber` of type `String`
  """
  phoneNumber: String
  """
  ✨ `_expr` server value variant of `phoneNumber` (✨ Generated from Field `User`.`phoneNumber` of type `String`)
  """
  phoneNumber_expr: String_Expr @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `User`.`role` of type `String!`
  """
  role: String
  """
  ✨ `_expr` server value variant of `role` (✨ Generated from Field `User`.`role` of type `String!`)
  """
  role_expr: String_Expr @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `User`.`harvestListings_on_farmer` of type `[HarvestListing!]!`
  """
  harvestListings_on_farmer: [HarvestListing_Data!]
  """
  ✨ Generated from Field `User`.`notifications_on_user` of type `[Notification!]!`
  """
  notifications_on_user: [Notification_Data!]
  """
  ✨ Generated from Field `User`.`orders_on_buyer` of type `[Order!]!`
  """
  orders_on_buyer: [Order_Data!]
  """
  ✨ Generated from Field `User`.`ponds_on_farmer` of type `[Pond!]!`
  """
  ponds_on_farmer: [Pond_Data!]
}
"""
✨ Generated filter input type for table 'User'. This input allows filtering objects using various conditions. Use `_or`, `_and`, and `_not` to compose complex filters.
"""
input User_Filter {
  """
  Apply multiple filter conditions using `AND` logic.
  """
  _and: [User_Filter!]
  """
  Negate the result of the provided filter condition.
  """
  _not: User_Filter
  """
  Apply multiple filter conditions using `OR` logic.
  """
  _or: [User_Filter!]
  """
  ✨ Generated from Field `User`.`id` of type `UUID!`
  """
  id: UUID_Filter
  """
  ✨ Generated from Field `User`.`createdAt` of type `Timestamp!`
  """
  createdAt: Timestamp_Filter
  """
  ✨ Generated from Field `User`.`displayName` of type `String`
  """
  displayName: String_Filter
  """
  ✨ Generated from Field `User`.`email` of type `String!`
  """
  email: String_Filter
  """
  ✨ Generated from Field `User`.`phoneNumber` of type `String`
  """
  phoneNumber: String_Filter
  """
  ✨ Generated from Field `User`.`role` of type `String!`
  """
  role: String_Filter
  """
  ✨ Generated from Field `User`.`harvestListings_on_farmer` of type `[HarvestListing!]!`
  """
  harvestListings_on_farmer: HarvestListing_ListFilter
  """
  ✨ Generated from Field `User`.`notifications_on_user` of type `[Notification!]!`
  """
  notifications_on_user: Notification_ListFilter
  """
  ✨ Generated from Field `User`.`orders_on_buyer` of type `[Order!]!`
  """
  orders_on_buyer: Order_ListFilter
  """
  ✨ Generated from Field `User`.`ponds_on_farmer` of type `[Pond!]!`
  """
  ponds_on_farmer: Pond_ListFilter
}
"""
✨ Generated first-row input type for table 'User'. This input selects the first row matching the filter criteria, ordered according to the specified conditions.
"""
input User_FirstRow {
  """
  Order the result by the specified fields.
  """
  orderBy: [User_Order!]
  """
  Filters rows based on the specified conditions.
  """
  where: User_Filter
}
"""
✨ Generated having input type for table 'User'. This input allows you to filter groups during aggregate queries using various conditions. Use `_or`, `_and`, and `_not` to compose complex filters.
"""
input User_Having {
  """
  Apply multiple Having conditions using `AND` logic.
  """
  _and: [User_Having!]
  """
  Whether to apply DISTINCT to the aggregate function.
  """
  _distinct: Boolean
  """
  Negate the result of the provided Having condition.
  """
  _not: User_Having
  """
  Apply multiple Having conditions using `OR` logic.
  """
  _or: [User_Having!]
  """
  ✨ Generated from Field `User`.`_count` of type `Int!`
  """
  _count: Int_Filter
  """
  ✨ Generated from Field `User`.`createdAt_count` of type `Int!`
  """
  createdAt_count: Int_Filter
  """
  ✨ Generated from Field `User`.`displayName_count` of type `Int!`
  """
  displayName_count: Int_Filter
  """
  ✨ Generated from Field `User`.`email_count` of type `Int!`
  """
  email_count: Int_Filter
  """
  ✨ Generated from Field `User`.`id_count` of type `Int!`
  """
  id_count: Int_Filter
  """
  ✨ Generated from Field `User`.`phoneNumber_count` of type `Int!`
  """
  phoneNumber_count: Int_Filter
  """
  ✨ Generated from Field `User`.`role_count` of type `Int!`
  """
  role_count: Int_Filter
  """
  ✨ Generated from Field `User`.`createdAt_min` of type `Timestamp`
  """
  createdAt_min: Timestamp_Filter
  """
  ✨ Generated from Field `User`.`createdAt_max` of type `Timestamp`
  """
  createdAt_max: Timestamp_Filter
}
"""
✨ Generated key input type for table 'User'. It represents the primary key fields used to uniquely identify a row in the table.
"""
input User_Key {
  """
  ✨ Generated from Field `User`.`id` of type `UUID!`
  """
  id: UUID
  """
  ✨ `_expr` server value variant of `id` (✨ Generated from Field `User`.`id` of type `UUID!`)
  """
  id_expr: UUID_Expr @fdc_forbiddenInVariables
}
"""
✨ Generated list filter input type for table 'User'. This input applies filtering logic based on the count or existence of related objects that matches certain criteria.
"""
input User_ListFilter {
  """
  The desired number of objects that match the condition (defaults to at least one).
  """
  count: Int_Filter = {gt:0}
  """
  Condition of the related objects to filter for.
  """
  exist: User_Filter
}
"""
✨ Generated order input type for table 'User'. This input defines the sorting order of rows in query results based on one or more fields.
"""
input User_Order {
  """
  ✨ Generated from Field `User`.`id` of type `UUID!`
  """
  id: OrderDirection
  """
  ✨ Generated from Field `User`.`createdAt` of type `Timestamp!`
  """
  createdAt: OrderDirection
  """
  ✨ Generated from Field `User`.`displayName` of type `String`
  """
  displayName: OrderDirection
  """
  ✨ Generated from Field `User`.`email` of type `String!`
  """
  email: OrderDirection
  """
  ✨ Generated from Field `User`.`phoneNumber` of type `String`
  """
  phoneNumber: OrderDirection
  """
  ✨ Generated from Field `User`.`role` of type `String!`
  """
  role: OrderDirection
  """
  ✨ Generated from Field `User`.`_count` of type `Int!`
  """
  _count: OrderDirection
  """
  ✨ Generated from Field `User`.`createdAt_count` of type `Int!`
  """
  createdAt_count: OrderDirection
  """
  ✨ Generated from Field `User`.`displayName_count` of type `Int!`
  """
  displayName_count: OrderDirection
  """
  ✨ Generated from Field `User`.`email_count` of type `Int!`
  """
  email_count: OrderDirection
  """
  ✨ Generated from Field `User`.`id_count` of type `Int!`
  """
  id_count: OrderDirection
  """
  ✨ Generated from Field `User`.`phoneNumber_count` of type `Int!`
  """
  phoneNumber_count: OrderDirection
  """
  ✨ Generated from Field `User`.`role_count` of type `Int!`
  """
  role_count: OrderDirection
  """
  ✨ Generated from Field `User`.`createdAt_min` of type `Timestamp`
  """
  createdAt_min: OrderDirection
  """
  ✨ Generated from Field `User`.`createdAt_max` of type `Timestamp`
  """
  createdAt_max: OrderDirection
}
